#  after "import Para"，call by "Para.(data_name)"
dataset = True  # True: load from file, False: generated by strict model

#Phy model setting
N_f = 1.0
Delta = 1.0
eps = 1e-15

#Temperature broadening
beta = 29 # 3  10   2.32
a = 1.0 * beta

#Dataset Para
## For EV
Num = 1171 #1201
alpha = 5.85
d_ev = 2*alpha/Num
quad_trapz = True # True False
## For omega
Num_omega = Num 
	# It is suggested that the calculation of loss converges better when “Num_omega = Num”####
alpha_omega = alpha * 1.2
d_omega = 2*alpha_omega/Num_omega

Noise = True
mean = 0
sigma = 0.0

#Finite temperature analog switch
Temp_if = True # True False

# Model selection
model = 0 # 0：Fully connected network  
#Model
node = 1000
N_layers = 10
activation2 = None #   'relu'   None  'selu'

#Model training
learning_rate = 0.001 / N_layers *1
nb_epochs = 10000
nb_update = 0